const express = require("express")
const Route = express.Router()
const admin = require("../controllers/admin")

Route
    .post("/login", admin.login)
    .post("/province-pos", admin.getSelectProvincePos)
    .post("/city-pos", admin.getSelectCityPos)
    .post("/order-pos", admin.getOrderPos)
    .post("/create-catalog-pos", admin.createCatalogPos)
    .post("/delete-catalog-pos", admin.deleteCatalogPos)
    .post("/update/:id/catalog-pos", admin.updateCatalogPos)
    .post("/catalog-pos", admin.getCatalogPosById)
    .post("/category-pos", admin.getCategoryPos)
    .post("/catalog-category-pos", admin.getCatalogPosCategoryById)
    .post("/add-cart-pos", admin.addToCartPos)
    .post("/cart-pos", admin.getPosCart)
    .post("/delete-cart-pos", admin.deleteCartPosById)
    .post("/clear-cart-pos", admin.clearCartPos)
    .post("/insert-order-pos", admin.insertOrderPos)
    .get("/remote", admin.remote)
    .get("/member", admin.getMember)
    .get("/member-report", admin.getMemberReport)
    .get("/member/excel", admin.memberToExcel)
    .get("/member-table", admin.memberTable)
    .get("/revenue", admin.revenue)
    .get("/summary", admin.summary)
    .get("/checkins", admin.checkins)
    .get("/checkin/:id", admin.checkinDetail)

module.exports = Route