const express = require("express")

const auth = require("./routes/auth")
const profile = require("./routes/profile")
const job = require("./routes/job")
const banner = require("./routes/banner")
const administration = require("./routes/administration")
const organization = require("./routes/organization")
const media = require("./routes/media")
const news = require("./routes/news")
const event = require("./routes/event")
const inbox = require("./routes/inbox")
const fcm = require("./routes/fcm")
const membernear = require("./routes/membernear")
const formOf = require("./routes/form_of")
const sos = require("./routes/sos")
const maintenance = require("./routes/maintenance")
const forum = require("./routes/forum")
const checkin = require("./routes/checkin")
const callback = require("./routes/callback")
const payment = require("./routes/payment")
const admin = require("./routes/admin")
const store = require("./routes/store")
const shippingAddress = require("./routes/shipping_address")
const product = require("./routes/product")
const order = require("./routes/order")
const cart = require("./routes/cart")
const checkout = require("./routes/checkout")
const dev = require("./routes/dev")
const pricelist = require("./routes/pricelist")

const Route = express.Router()

Route
    .use("/api/v1/auth", auth)
    .use("/user-service/profile", profile)
    .use("/api/v1/banner", banner)
    .use("/api/v1/organization", organization)
    .use("/api/v1/media", media)
    .use("/api/v1/administration", administration)
    .use("/api/v1/job", job)
    .use("/api/v1/inbox", inbox)
    .use("/api/v1/checkin", checkin)
    .use("/api/v1/maintenance", maintenance)
    .use("/api/v1/fcm", fcm)
    .use("/api/v1/forum", forum)
    .use("/api/v1/membernear", membernear)
    .use("/api/v1/callback", callback)
    .use("/api/v1/payment", payment)
    .use("/api/v1/form", formOf)
    .use("/api/v1/sos", sos)
    .use("/api/v1/event", event)
    .use("/api/v1/admin", admin)
    .use("/api/v1/news", news)
    .use("/api/v1/store", store)
    .use("/api/v1/shipping-address", shippingAddress)
    .use("/api/v1/product", product)
    .use("/api/v1/order", order)
    .use('/api/v1/cart', cart)
    .use("/api/v1/checkout", checkout)
    .use("/api/v1/dev", dev)
    .use("/api/v1/pricelist", pricelist)

module.exports = Route